services:
  app:
    container_name: hotel_manager
    restart: always
    build: ./Hotel_App
    ports:
      - '80:80'
    links:
      - mongo
  mongo:
    container_name: MongoDB
    image: mongo:4
    volumes:
      - ./database:/data/db
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null 

